[2019-12-18 23:13:31,112] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY2ODU2MTEsIm5iZiI6MTU3NjY4NTYxMSwianRpIjoiMTRjYWFhNjYtYjJkOC00ZGIwLWE0OTktM2Y2MWY2NDgzMWZiIiwiZXhwIjoxNTc2Njg3NDExLCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.TDaAlYzozMeb40SdoBTDS-c7gowYNhnKOjflh_axorQ"}}
[2019-12-18 23:25:59,590] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY2ODYzNTksIm5iZiI6MTU3NjY4NjM1OSwianRpIjoiMDRhMzUwYzUtMTA1Zi00NDg1LTkyYTktZDZkZDQ0MmQ5YWRiIiwiZXhwIjoxNTc2Njg4MTU5LCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.x0HZIGFgNmUd-Qni_wLTiBw7uIaLLeUKFUxgcL6KUrw"}}
[2019-12-18 23:26:13,267] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY2ODYzNzMsIm5iZiI6MTU3NjY4NjM3MywianRpIjoiYjFjYTUyZGEtMTNjYy00YWJiLTk0ZTgtYmVhMjMyOTkxNTcxIiwiZXhwIjoxNTc2Njg4MTczLCJpZGVudGl0eSI6Indhd2V3MiIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7ImlkIjoyLCJjbGllbnRfa2V5Ijoid2F3ZXcyIiwic3RhdHVzIjpmYWxzZSwiaW50ZXJuYWxfc3RhdHVzIjpmYWxzZX19.U65RytxiLbXMMaKB1_UyeKdxbUTasCr325gBIX-6L80"}}
[2019-12-18 23:26:25,449] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"book_id": 4, "user_id": 1}, "response": [{"created_at": "Tue, 17 Dec 2019 23:04:22 -0000", "return_date": "Tue, 24 Dec 2019 23:04:22 -0000", "id": 2, "book_id": 1, "user_id": 2, "user": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 2, "name": "Wildan2", "age": 22, "sex": "Male", "client_id": 2}, "book": {"created_at": "Tue, 17 Dec 2019 21:25:33 -0000", "updated_at": "Tue, 17 Dec 2019 21:25:33 -0000", "id": 1, "title": "Judul Buku Satu", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}}, {"created_at": "Tue, 17 Dec 2019 23:04:22 -0000", "return_date": "Tue, 24 Dec 2019 23:04:22 -0000", "id": 4, "book_id": 2, "user_id": 2, "user": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 2, "name": "Wildan2", "age": 22, "sex": "Male", "client_id": 2}, "book": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 2, "title": "Judul Buku Dua", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}}, {"created_at": "Tue, 17 Dec 2019 23:30:39 -0000", "return_date": "Tue, 24 Dec 2019 23:30:39 -0000", "id": 6, "book_id": 3, "user_id": 2, "user": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 2, "name": "Wildan2", "age": 22, "sex": "Male", "client_id": 2}, "book": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 3, "title": "Judul Buku Tiga", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}}]}
[2019-12-18 23:27:08,012] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY2ODY0MjgsIm5iZiI6MTU3NjY4NjQyOCwianRpIjoiOTI3ZjViYmUtYmFlOC00ZGVkLWJhMzgtNjZmMDRlZDg0ZTkxIiwiZXhwIjoxNTc2Njg4MjI4LCJpZGVudGl0eSI6Indhd2V3MSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7ImlkIjoxLCJjbGllbnRfa2V5Ijoid2F3ZXcxIiwic3RhdHVzIjpmYWxzZSwiaW50ZXJuYWxfc3RhdHVzIjpmYWxzZX19.n5MsWtdj0KI2zF1okTbt4HxFbaXZlGl3dVpDW8wngV0"}}
[2019-12-18 23:27:20,980] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"book_id": 4, "user_id": 1}, "response": [{"created_at": "Tue, 17 Dec 2019 23:04:22 -0000", "return_date": "Tue, 24 Dec 2019 23:04:22 -0000", "id": 1, "book_id": 1, "user_id": 1, "user": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 11:53:13 -0000", "id": 1, "name": "Wildan Firdaus", "age": 22, "sex": "Male", "client_id": 1}, "book": {"created_at": "Tue, 17 Dec 2019 21:25:33 -0000", "updated_at": "Tue, 17 Dec 2019 21:25:33 -0000", "id": 1, "title": "Judul Buku Satu", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}}, {"created_at": "Tue, 17 Dec 2019 23:04:22 -0000", "return_date": "Tue, 24 Dec 2019 23:04:22 -0000", "id": 3, "book_id": 2, "user_id": 1, "user": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 11:53:13 -0000", "id": 1, "name": "Wildan Firdaus", "age": 22, "sex": "Male", "client_id": 1}, "book": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 2, "title": "Judul Buku Dua", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}}, {"created_at": "Tue, 17 Dec 2019 23:26:46 -0000", "return_date": "Tue, 24 Dec 2019 23:26:46 -0000", "id": 5, "book_id": 3, "user_id": 1, "user": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 11:53:13 -0000", "id": 1, "name": "Wildan Firdaus", "age": 22, "sex": "Male", "client_id": 1}, "book": {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 3, "title": "Judul Buku Tiga", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}}]}
[2019-12-19 00:12:58,561] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "400 BAD REQUEST", "request": null, "response": {"message": {"client_key": "Missing required parameter in the query string"}}}
[2019-12-19 00:13:49,331] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "401 UNAUTHORIZED", "request": null, "response": {"status": "UNAUTHORIZED", "message": "invalid client_key or client_secret"}}
[2019-12-19 00:14:22,878] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY2ODkyNjIsIm5iZiI6MTU3NjY4OTI2MiwianRpIjoiZjUxMWE0Y2MtYTQ3ZS00ODc0LTk2OTMtYWU1NGE1YzJhOGI4IiwiZXhwIjoxNTc2NjkxMDYyLCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.ApBSuNwRvcwx6Py2njpit7lCDsGiYSF2LxrtysudblU"}}
[2019-12-19 00:14:39,476] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": [{"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:09:51 -0000", "id": 1, "client_key": "wawew1", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:00 -0000", "id": 2, "client_key": "wawew2", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:11 -0000", "id": 3, "client_key": "wawew3", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 11:53:13 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:20 -0000", "id": 4, "client_key": "wawew4", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 21:05:16 -0000", "updated_at": "Wed, 18 Dec 2019 21:05:16 -0000", "id": 6, "client_key": "wawew5", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": true}]}
[2019-12-19 00:14:51,422] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "400 BAD REQUEST", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": {"p": "invalid literal for int() with base 10: ''"}}}
[2019-12-19 00:15:12,971] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": [{"created_at": "Wed, 18 Dec 2019 21:05:16 -0000", "updated_at": "Wed, 18 Dec 2019 21:05:16 -0000", "id": 6, "client_key": "wawew5", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": true}]}
[2019-12-19 00:15:24,365] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": []}
[2019-12-19 00:15:32,503] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": [{"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:09:51 -0000", "id": 1, "client_key": "wawew1", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:00 -0000", "id": 2, "client_key": "wawew2", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:11 -0000", "id": 3, "client_key": "wawew3", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 11:53:13 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:20 -0000", "id": 4, "client_key": "wawew4", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 21:05:16 -0000", "updated_at": "Wed, 18 Dec 2019 21:05:16 -0000", "id": 6, "client_key": "wawew5", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": true}]}
[2019-12-19 00:16:17,497] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "400 BAD REQUEST", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": {"status": "Invalid literal for boolean(): wa"}}}
[2019-12-19 00:16:48,053] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "400 BAD REQUEST", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": {"rp": "invalid literal for int() with base 10: 'z'"}}}
[2019-12-19 00:18:40,953] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "400 BAD REQUEST", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": {"status": "Invalid literal for boolean(): wa"}}}
[2019-12-19 07:02:45,348] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /client [GET]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 294, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/utils.py", line 118, in decode_token
    allow_expired=allow_expired
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/tokens.py", line 140, in decode_jwt
    leeway=leeway, options=options, issuer=issuer)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/jwt/api_jwt.py", line 104, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/jwt/api_jwt.py", line 134, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/jwt/api_jwt.py", line 175, in _validate_exp
    raise ExpiredSignatureError('Signature has expired')
jwt.exceptions.ExpiredSignatureError: Signature has expired
[2019-12-19 07:02:45,350] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": "Internal Server Error"}}
[2019-12-19 07:02:55,425] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY3MTM3NzUsIm5iZiI6MTU3NjcxMzc3NSwianRpIjoiZDNiZjU1NzMtY2YxOC00NmY0LWJmZTktOGNiYTQxY2UxYWM3IiwiZXhwIjoxNTc2NzE1NTc1LCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.B4huK6CJYuZLJDe98CmY51i-XbtjJfZy4tzpfG7d6Uk"}}
[2019-12-19 07:03:11,494] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "400 BAD REQUEST", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": {"status": "Invalid literal for boolean(): wa"}}}
[2019-12-19 07:03:19,196] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": [{"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:09:51 -0000", "id": 1, "client_key": "wawew1", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:00 -0000", "id": 2, "client_key": "wawew2", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:11 -0000", "id": 3, "client_key": "wawew3", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 11:53:13 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:20 -0000", "id": 4, "client_key": "wawew4", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 21:05:16 -0000", "updated_at": "Wed, 18 Dec 2019 21:05:16 -0000", "id": 6, "client_key": "wawew5", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": true}]}
[2019-12-19 07:03:53,443] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {}, "response": [{"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:09:51 -0000", "id": 1, "client_key": "wawew1", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:00 -0000", "id": 2, "client_key": "wawew2", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:11 -0000", "id": 3, "client_key": "wawew3", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 11:53:13 -0000", "updated_at": "Wed, 18 Dec 2019 18:10:20 -0000", "id": 4, "client_key": "wawew4", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": false}, {"created_at": "Wed, 18 Dec 2019 21:05:16 -0000", "updated_at": "Wed, 18 Dec 2019 21:05:16 -0000", "id": 6, "client_key": "wawew5", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": true}]}
[2019-12-19 07:04:03,300] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:04:13,881] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:04:20,775] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:04:34,171] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "400 BAD REQUEST", "request": {"client_key": "wawew5", "status": true}, "response": {"message": {"client_secret": "Missing required parameter in the JSON body"}}}
[2019-12-19 07:04:44,174] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:07:08,827] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:07:13,297] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:09:00,883] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /client/4 [POST]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py", line 34, in wrapper
    return fn(*args, **kwargs)
TypeError: post() got an unexpected keyword argument 'id'
[2019-12-19 07:09:00,884] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-19 07:09:06,230] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /client/1 [POST]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py", line 34, in wrapper
    return fn(*args, **kwargs)
TypeError: post() got an unexpected keyword argument 'id'
[2019-12-19 07:09:06,232] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-19 07:09:18,352] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:09:42,126] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:10:12,706] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:10:26,668] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "404 NOT FOUND", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": "NOT_FOUND"}}
[2019-12-19 07:22:44,069] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "PUT", "code": "400 BAD REQUEST", "request": {}, "response": {"message": "The browser (or proxy) sent a request that this server could not understand."}}
[2019-12-19 07:44:16,241] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY3MTYyNTYsIm5iZiI6MTU3NjcxNjI1NiwianRpIjoiMjk1MmE3MTctNmY2Ni00ZTYyLWJmYjItNjM5MzFkMmEwODdjIiwiZXhwIjoxNTc2NzE4MDU2LCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.kOHdrx4T8wf4CKfQUpafzIFgIxvCySJ6HIwSPPTM3Yk"}}
[2019-12-19 07:44:33,456] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"title": "Judul Buku Tiga", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}, "response": [{"created_at": "Tue, 17 Dec 2019 21:25:33 -0000", "updated_at": "Tue, 17 Dec 2019 21:25:33 -0000", "id": 1, "title": "Judul Buku Satu", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 2, "title": "Judul Buku Dua", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}, {"created_at": "Tue, 17 Dec 2019 21:45:05 -0000", "updated_at": "Tue, 17 Dec 2019 21:45:05 -0000", "id": 3, "title": "Judul Buku Tiga", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}]}
[2019-12-19 07:44:44,415] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"title": "Judul Buku Tiga", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}, "response": []}
[2019-12-19 07:44:54,108] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": {"title": "Judul Buku Tiga", "isbn": "1-234-5678-9101112-13", "writer": "Dr. Who"}, "response": []}
[2019-12-19 09:53:09,622] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "404 NOT FOUND", "request": null, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2019-12-19 09:54:18,050] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "404 NOT FOUND", "request": null, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2019-12-19 09:54:45,116] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "404 NOT FOUND", "request": null, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2019-12-19 09:54:50,587] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "404 NOT FOUND", "request": null, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2019-12-19 09:55:45,341] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "404 NOT FOUND", "request": null, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2019-12-19 09:56:38,268] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "404 NOT FOUND", "request": null, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2019-12-19 09:57:34,799] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /weather [GET]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
[2019-12-19 09:57:34,801] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "request": null, "response": {"message": "Internal Server Error"}}
[2019-12-19 09:57:59,948] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /weather [GET]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/weather/__init__.py", line 24, in get
    lon = geo["longtitude"]
KeyError: 'longtitude'
[2019-12-19 09:57:59,951] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "request": null, "response": {"message": "Internal Server Error"}}
[2019-12-19 09:58:46,491] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /weather [GET]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/weather/__init__.py", line 34, in get
    "date": current["data"][0]["datetime"],
KeyError: 'data'
[2019-12-19 09:58:46,495] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "request": null, "response": {"message": "Internal Server Error"}}
[2019-12-19 10:00:08,400] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /weather [GET]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/weather/__init__.py", line 34, in get
    "date": current["data"][0]["datetime"],
KeyError: 'data'
[2019-12-19 10:00:08,405] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "request": null, "response": {"message": "Internal Server Error"}}
[2019-12-19 10:01:24,178] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"city": "Surabaya", "organization": "AS24203 PT Excelcomindo Pratama (Network Access Provider)", "timezone": "Asia/Jakarta", "current_weather": {"date": "2019-12-19:02", "temp": 34.6}}}
[2019-12-19 10:03:18,179] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"city": "Surabaya", "organization": "AS24203 PT Excelcomindo Pratama (Network Access Provider)", "timezone": "Asia/Jakarta", "current_weather": {"date": "2019-12-19:02", "temp": 34.6}}}
[2019-12-19 10:07:39,331] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"city": "Surabaya", "organization": "AS24203 PT Excelcomindo Pratama (Network Access Provider)", "timezone": "Asia/Jakarta", "current_weather": {"date": "2019-12-19:02", "temp": 34.6}}}
[2019-12-19 15:35:49,177] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY3NDQ1NDksIm5iZiI6MTU3Njc0NDU0OSwianRpIjoiYzQ4YWI0ZTQtZDExNy00YTM3LWIwOTItNDhhMTc4MzBiYmM4IiwiZXhwIjoxNTc2NzQ2MzQ5LCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.bIFPF9xxtYG-uoHaaFc1JEnbdvxhovq3Y53HiaCEYzM", "message": "token created"}}
[2019-12-19 15:36:15,434] {/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /client [POST]
Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'wawew5' for key 'client_key'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py", line 34, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/client/resources.py", line 62, in post
    db.session.commit()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements
    statement, params
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/alta-18/Documents/Alterra/FlaskPractice/.flaskblog_venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'wawew5' for key 'client_key'")
[SQL: INSERT INTO clients (client_key, client_secret, status, created_at, updated_at, deleted_status) VALUES (%(client_key)s, %(client_secret)s, %(status)s, %(created_at)s, %(updated_at)s, %(deleted_status)s)]
[parameters: {'client_key': 'wawew5', 'client_secret': '399d8020dcd55e67a23dcea5b646e583', 'status': 1, 'created_at': datetime.datetime(2019, 12, 19, 15, 35, 44, 120370), 'updated_at': datetime.datetime(2019, 12, 19, 15, 35, 44, 120407), 'deleted_status': 0}]
(Background on this error at: http://sqlalche.me/e/gkpj)
[2019-12-19 15:36:15,457] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"message": "Internal Server Error"}}
[2019-12-19 15:37:12,513] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY3NDQ2MzIsIm5iZiI6MTU3Njc0NDYzMiwianRpIjoiYzkzYjVlMGUtZjVmOC00YTFiLTk5M2EtNThmZjg1OWYwNGY5IiwiZXhwIjoxNTc2NzQ2NDMyLCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.1j9hsD1K8qXoTv138Z4vPIpK86jLoHg8osJTZBjEaco", "message": "token created"}}
[2019-12-19 15:37:22,603] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "request": {"client_key": "wawew5", "client_secret": "wawew123", "status": true}, "response": {"status": "FAILED", "message": "client_key already exist"}}
[2019-12-19 15:37:36,087] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "request": {"client_key": "wawew10", "client_secret": "wawew123", "status": true}, "response": {"status": "FAILED", "message": "client_key already exist"}}
[2019-12-19 15:38:50,889] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "GET", "code": "200 OK", "request": null, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzY3NDQ3MzAsIm5iZiI6MTU3Njc0NDczMCwianRpIjoiYzdhZTc5NDMtNzA3My00MTM1LWFiZTEtMjkyNzZhZDFmYTUwIiwiZXhwIjoxNTc2NzQ2NTMwLCJpZGVudGl0eSI6ImludGVybmFsIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiaW50ZXJuYWxfc3RhdHVzIjp0cnVlfX0.TekIWiaaGSjMcKzpTzmqMOF6EPqM00VU6ytEYIhj7Qw", "message": "token created"}}
[2019-12-19 15:39:09,745] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "request": {"client_key": "wawew9", "client_secret": "wawew123", "status": true}, "response": {"status": "FAILED", "message": "client_key already exist"}}
[2019-12-19 15:39:18,152] {/home/alta-18/Documents/Alterra/FlaskPractice/blueprints/__init__.py:63} INFO - REQUEST_LOG	{"method": "POST", "code": "200 OK", "request": {"client_key": "wawew10", "client_secret": "wawew123", "status": true}, "response": {"created_at": "Thu, 19 Dec 2019 15:38:43 -0000", "updated_at": "Thu, 19 Dec 2019 15:38:43 -0000", "id": 11, "client_key": "wawew10", "client_secret": "399d8020dcd55e67a23dcea5b646e583", "status": true}}
